---
datacenter:
  children:
    routers:
      hosts:
        192.168.1.7[1:3]:
      vars:
        testVar: 999
    switches:
      hosts:
        192.168.1.8[1:3]:

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_ssh_psw: admin
    ntp_servers:
      - 10.30.11.10
      - 10.20.11.10
